var city={
	"typelist":[
		{
			"type":1,
			"typeName":"美食名城",
			"sightList":[
				{
					"name":"北京",
					"code":"PEK",
					"summary":"追溯帝王盛世的旅程，看古现代文明的交融",
					"coverImg":"bj.jpg",
					"photos":["1.jpg","2.jpg","3.jpg"]
				},
				{
					"name":"成都",
					"code":"CTU",
					"summary":"一个让你停下脚步开动味蕾的火辣城市",
					"coverImg":"cd.jpg",
					"photos":["1.jpg","2.jpg","3.jpg"]
				},
				{
					"name":"西安",
					"code":"XIY",
					"summary":"到处都写着历史两个字",
					"coverImg":"xa.jpg",
					"photos":["1.jpg","2.jpg","3.jpg"]
				},
				{
					"name":"武汉",
					"code":"WUH",
					"summary":"黄鹤楼中吹玉笛，江城五月落梅花",
					"coverImg":"wh.jpg",
					"photos":["1.jpg","2.jpg","3.jpg"]
				},
				{
					"name":"南京",
					"code":"NKG",
					"summary":"秦淮风光，六朝古都",
					"coverImg":"nj.jpg",
					"photos":["1.jpg","2.jpg","3.jpg"]
				},
				{
					"name":"上海",
					"code":"SHA",
					"summary":"西方与东方文化交融的远东第一城",
					"coverImg":"sh.jpg",
					"photos":["1.jpg","2.jpg","3.jpg"]
				},
				{
					"name":"重庆",
					"code":"CKG",
					"summary":"美食、美女，一场关于眼睛与嘴巴的旅行",
					"coverImg":"cq.jpg",
					"photos":["1.jpg","2.jpg","3.jpg"]
				},
				{
					"name":"广州",
					"code":"CAN",
					"summary":"“美食天堂”、“生活之城”著称的国际大都会",
					"coverImg":"gz.jpg",
					"photos":["1.jpg","2.jpg","3.jpg"]
				},
				{
					"name":"深圳",
					"code":"SZX",
					"summary":"带你体会现代化的繁华与美丽",
					"coverImg":"sz.jpg",
					"photos":["1.jpg","2.jpg","3.jpg"]
				},
				{
					"name":"长沙",
					"code":"CSX",
					"summary":"一座能够给你无限欢乐的城市",
					"coverImg":"cs.jpg",
					"photos":["1.jpg","2.jpg","3.jpg"]
				},
				{
					"name":"南宁",
					"code":"NNG",
					"summary":"边陲古镇却有着别样的神秘",
					"coverImg":"nn.jpg",
					"photos":["1.jpg","2.jpg","3.jpg"]
				},
				{
					"name":"太原",
					"code":"TYN",
					"summary":"在美食与历史遗迹中领略文化名城",
					"coverImg":"ty.jpg",
					"photos":["1.jpg","2.jpg","3.jpg"]
				},
				{
					"name":"郑州",
					"code":"CGO",
					"summary":"夏文明的发源地，承载着璀璨的千年文明",
					"coverImg":"zz.jpg",
					"photos":["1.jpg","2.jpg","3.jpg"]
				},
			]
		},
		{
			"type":2,
			"typeName":"欢享海滨",
			"sightList":[
				{
					"name":"厦门",
					"code":"XMN",
					"summary":"文艺范是鼓浪屿和文艺青年的名片",
					"coverImg":"xm.jpg",
					"photos":["1.jpg","2.jpg","3.jpg"]
				},
				{
					"name":"青岛",
					"code":"TAO",
					"summary":"去海边吃着海鲜唱着歌如何",
					"coverImg":"qd.jpg",
					"photos":["1.jpg","2.jpg","3.jpg"]
				},
				{
					"name":"三亚",
					"code":"SYX",
					"summary":"这里不只有中国最美的海滩",
					"coverImg":"SY.jpg",
					"photos":["1.jpg","2.jpg","3.jpg"]
				},
				{
					"name":"海口",
					"code":"HAK",
					"summary":"气候宜人，休闲度假首选之地",
					"coverImg":"HK.jpg",
					"photos":["1.jpg","2.jpg","3.jpg"]
				},
				{
					"name":"福州",
					"code":"FOC",
					"summary":"是江南圣地，也是中国的“佛国”",
					"coverImg":"FZ.jpg",
					"photos":["1.jpg","2.jpg","3.jpg"]
				},
				{
					"name":"天津",
					"code":"TSN",
					"summary":"中西合璧，这里有抑郁的风情和美丽",
					"coverImg":"TJ.jpg",
					"photos":["1.jpg","2.jpg","3.jpg"]
				},
			]
		},
		{
			"type":3,
			"typeName":"避暑胜地",
			"sightList":[
				{
					"name":"昆明",
					"code":"KMG",
					"summary":"一座阳光总在屋子里的城市",
					"coverImg":"KM.jpg",
					"photos":["1.jpg","2.jpg","3.jpg"]
				},
				{
					"name":"贵阳",
					"code":"KWE",
					"summary":"没有夏日炎炎，天然的避暑之都",
					"coverImg":"GY.jpg",
					"photos":["1.jpg","2.jpg","3.jpg"]
				},
				{
					"name":"杭州",
					"code":"HGH",
					"summary":"人间的天堂，流连忘返",
					"coverImg":"HZ.jpg",
					"photos":["1.jpg","2.jpg","3.jpg"]
				},
				{
					"name":"沈阳",
					"code":"SHE",
					"summary":"东北地区第一大城市",
					"coverImg":"SY.jpg",
					"photos":["1.jpg","2.jpg","3.jpg"]
				},
				{
					"name":"哈尔滨",
					"code":"HRB",
					"summary":"中欧文明共同创造了这座“东方莫斯科”",
					"coverImg":"HEB.jpg",
					"photos":["1.jpg","2.jpg","3.jpg"]
				},
				{
					"name":"大连",
					"code":"DLC",
					"summary":"中国北方绿化最好的城市",
					"coverImg":"DL.jpg",
					"photos":["1.jpg","2.jpg","3.jpg"]
				},
				{
					"name":"长春",
					"code":"CGQ",
					"summary":"一座会让你忘了黑土地的北方“林园城市”",
					"coverImg":"CC.jpg",
					"photos":["1.jpg","2.jpg","3.jpg"]
				},
				{
					"name":"济南",
					"code":"TNA",
					"summary":"大明湖畔的夏雨荷依然让人心肠百转",
					"coverImg":"JN.jpg",
					"photos":["1.jpg","2.jpg","3.jpg"]
				},
				{
					"name":"乌鲁木齐",
					"code":"URC",
					"summary":"47个民族的文化在这里绽放光彩",
					"coverImg":"WLMQ.jpg",
					"photos":["1.jpg","2.jpg","3.jpg"]
				},
				{
					"name":"丽江",
					"code":"LJG",
					"summary":"漫步古城，让午后的阳光温暖你最柔软的内心",
					"coverImg":"LJ.jpg",
					"photos":["1.jpg","2.jpg","3.jpg"]
				},
			]
		}
	]
}
